services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: landingCV
    image: landing_cv_app:latest
    restart: always
    volumes:
      - landing_cv_img:/var/www/html/public/storage:rw,z
      - /var/www/storage
      - /var/www/bootstrap/cache
      - landing_cv_storage:/var/www/public/build:rw,z
    working_dir: /var/www/html
    user: "www-data"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: mysql:8.4.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
  
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    image: landing_cv_server:latest
    restart: always
    volumes:
      - landing_cv_img:/var/www/html/public/storage:ro,z
      - landing_cv_storage:/var/www/html/public/build:ro,z
    ports:
      - "8080:80"
    container_name: nginx
    depends_on:
      - web
  
  dbms:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_PORT: 3306
    container_name: phpmyadmin
    depends_on:
      - web
      - db

volumes:
  mysql_data:

  landing_cv_img:

  landing_cv_storage: